# Generated by Django 5.1.5 on 2025-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nosotros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
