# Generated by Django 5.1.5 on 2025-02-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_carrusel_descripcion_alter_carrusel_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Enlace de WhatsApp completo (incluyendo https://)')),
            ],
            options={
                'verbose_name': 'Enlace de WhatsApp',
                'verbose_name_plural': 'Enlace de WhatsApp',
            },
        ),
    ]
